//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chldr_shared.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chldr_shared.Resources.Localizations.AppLocalizations", typeof(AppLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjective.
        /// </summary>
        public static string Adjective {
            get {
                return ResourceManager.GetString("Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverb.
        /// </summary>
        public static string Adverb {
            get {
                return ResourceManager.GetString("Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chechen Language Dictionary.
        /// </summary>
        public static string App_title {
            get {
                return ResourceManager.GetString("App_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic form.
        /// </summary>
        public static string Basic_form {
            get {
                return ResourceManager.GetString("Basic_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and follow the instructions.
        /// </summary>
        public static string Check_your_email_and_follow_instructions {
            get {
                return ResourceManager.GetString("Check_your_email_and_follow_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string Choose_language {
            get {
                return ResourceManager.GetString("Choose_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Vu, Bu / Du.
        /// </summary>
        public static string Class_1_vu_bd {
            get {
                return ResourceManager.GetString("Class:1_vu_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Yu, Bu / Du.
        /// </summary>
        public static string Class_2_yu_bd {
            get {
                return ResourceManager.GetString("Class:2_yu_bd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Yu, Yu.
        /// </summary>
        public static string Class_3_yu_yu {
            get {
                return ResourceManager.GetString("Class:3_yu_yu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Du, Du.
        /// </summary>
        public static string Class_4_du_du {
            get {
                return ResourceManager.GetString("Class:4_du_du", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Bu, Bu / Yu.
        /// </summary>
        public static string Class_5_bu_by {
            get {
                return ResourceManager.GetString("Class:5_bu_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Bu, Du.
        /// </summary>
        public static string Class_6_b_d {
            get {
                return ResourceManager.GetString("Class:6_b_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;Hello and Welcome!&lt;/span&gt;&lt;/h2&gt;&lt;p&gt;&lt;span style=&apos;font-size:14px&apos;&gt;We&amp;#39;re delighted to have you on board with us! Let&amp;#39;s make Chechen great again!&lt;br /&gt;\r\nTo activate your account, please follow &lt;a href=&apos;{0}&apos;&gt;this link&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&apos;font-size:12px&apos;&gt;This email is auto-generated, do not reply to it, you can always reach us via team@nohchiyn-mott.com&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Email_Confirm_email_html {
            get {
                return ResourceManager.GetString("Email:Confirm_email_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email.
        /// </summary>
        public static string Email_Confirm_email_subject {
            get {
                return ResourceManager.GetString("Email:Confirm_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;Password reset request&lt;/span&gt;&lt;/h2&gt;
        ///
        ///&lt;p&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;We&amp;#39;have received a request to reset your password, please proceed with the link to set a new password, or ignore the message if you didn&amp;#39;t start this process.&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;&lt;a href=&apos;{0}&apos;&gt;Set a new password&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_Reset_password_html {
            get {
                return ResourceManager.GetString("Email:Reset_password_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string Email_Reset_password_subject {
            get {
                return ResourceManager.GetString("Email:Reset_password_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string Email_sent {
            get {
                return ResourceManager.GetString("Email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string Error_Email_not_valid {
            get {
                return ResourceManager.GetString("Error:Email_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string Error_Invalid_name {
            get {
                return ResourceManager.GetString("Error:Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only have latin letters and digits.
        /// </summary>
        public static string Error_Invalid_username {
            get {
                return ResourceManager.GetString("Error:Invalid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long.
        /// </summary>
        public static string Error_Password_too_long {
            get {
                return ResourceManager.GetString("Error:Password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string Error_Passwords_dont_match {
            get {
                return ResourceManager.GetString("Error:Passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string Error_Passwords_is_not_valid {
            get {
                return ResourceManager.GetString("Error:Passwords_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation language must be set.
        /// </summary>
        public static string Error_Translation_language_must_be_set {
            get {
                return ResourceManager.GetString("Error:Translation_language_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation text must be set.
        /// </summary>
        public static string Error_Translation_text_must_be_set {
            get {
                return ResourceManager.GetString("Error:Translation_text_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word content must be set.
        /// </summary>
        public static string Error_Word_content_must_be_set {
            get {
                return ResourceManager.GetString("Error:Word_content_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammatical class.
        /// </summary>
        public static string Grammatical_class {
            get {
                return ResourceManager.GetString("Grammatical_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code.
        /// </summary>
        public static string Language_code {
            get {
                return ResourceManager.GetString("Language_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noun.
        /// </summary>
        public static string Noun {
            get {
                return ResourceManager.GetString("Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or sign up with:.
        /// </summary>
        public static string Or_sign_up_with_ {
            get {
                return ResourceManager.GetString("Or_sign_up_with:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string Password_reset {
            get {
                return ResourceManager.GetString("Password_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        public static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successful, please check your email and follow the included link to activate your profile..
        /// </summary>
        public static string Registration_email_sent_message {
            get {
                return ResourceManager.GetString("Registration_email_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new password.
        /// </summary>
        public static string Set_new_password {
            get {
                return ResourceManager.GetString("Set_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing ....
        /// </summary>
        public static string Start_typing {
            get {
                return ResourceManager.GetString("Start_typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb.
        /// </summary>
        public static string Verb {
            get {
                return ResourceManager.GetString("Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset your password here.
        /// </summary>
        public static string You_can_reset_your_password_here {
            get {
                return ResourceManager.GetString("You_can_reset_your_password_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated.
        /// </summary>
        public static string Your_password_has_been_updated {
            get {
                return ResourceManager.GetString("Your_password_has_been_updated", resourceCulture);
            }
        }
    }
}
