//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain.Resources.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("domain.Resources.Localizations.AppLocalizations", typeof(AppLocalizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Ask.
        /// </summary>
        public static string AddAsk {
            get {
                return ResourceManager.GetString("AddAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chechen Language Dictionary.
        /// </summary>
        public static string App_title {
            get {
                return ResourceManager.GetString("App_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic form.
        /// </summary>
        public static string Basic_form {
            get {
                return ResourceManager.GetString("Basic_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and follow the instructions.
        /// </summary>
        public static string Check_your_email_and_follow_instructions {
            get {
                return ResourceManager.GetString("Check_your_email_and_follow_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string Choose_language {
            get {
                return ResourceManager.GetString("Choose_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Vu, Bu / Du.
        /// </summary>
        public static string Class_1_v_b {
            get {
                return ResourceManager.GetString("Class:1_v_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Yu, Bu / Du.
        /// </summary>
        public static string Class_2_y_b {
            get {
                return ResourceManager.GetString("Class:2_y_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Yu, Yu.
        /// </summary>
        public static string Class_3_y_y {
            get {
                return ResourceManager.GetString("Class:3_y_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Du, Du.
        /// </summary>
        public static string Class_4_d_d {
            get {
                return ResourceManager.GetString("Class:4_d_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Bu, Bu / Yu.
        /// </summary>
        public static string Class_5_b_b {
            get {
                return ResourceManager.GetString("Class:5_b_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Bu, Du.
        /// </summary>
        public static string Class_6_b_d {
            get {
                return ResourceManager.GetString("Class:6_b_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributor.
        /// </summary>
        public static string Contributor {
            get {
                return ResourceManager.GetString("Contributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;Hello and Welcome!&lt;/span&gt;&lt;/h2&gt;&lt;p&gt;&lt;span style=&apos;font-size:14px&apos;&gt;We&amp;#39;re delighted to have you on board with us! Let&amp;#39;s make Chechen great again!&lt;br /&gt;\r\nTo activate your account, please follow &lt;a href=&apos;{0}&apos;&gt;this link&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;&lt;p&gt;&lt;span style=&apos;font-size:12px&apos;&gt;This email is auto-generated, do not reply to it, you can always reach us via support@dosham.app&lt;/span&gt;&lt;/p&gt;.
        /// </summary>
        public static string Email_Confirm_email_html {
            get {
                return ResourceManager.GetString("Email:Confirm_email_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email.
        /// </summary>
        public static string Email_Confirm_email_subject {
            get {
                return ResourceManager.GetString("Email:Confirm_email_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;Password reset request&lt;/span&gt;&lt;/h2&gt;
        ///
        ///&lt;p&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;We&amp;#39;have received a request to reset your password, please proceed with the link to set a new password, or ignore the message if you didn&amp;#39;t start this process.&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&lt;span style=&apos;font-family:Lucida Sans Unicode,Lucida Grande,sans-serif&apos;&gt;&lt;a href=&apos;{0}&apos;&gt;Set a new password&lt;/a&gt;&lt;/span&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Email_Reset_password_html {
            get {
                return ResourceManager.GetString("Email:Reset_password_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        public static string Email_Reset_password_subject {
            get {
                return ResourceManager.GetString("Email:Reset_password_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string Email_sent {
            get {
                return ResourceManager.GetString("Email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter translation notes.
        /// </summary>
        public static string Enter_translation_notes {
            get {
                return ResourceManager.GetString("Enter_translation_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter translation text.
        /// </summary>
        public static string Enter_translation_text {
            get {
                return ResourceManager.GetString("Enter_translation_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter word.
        /// </summary>
        public static string EnterWord {
            get {
                return ResourceManager.GetString("EnterWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enthusiast.
        /// </summary>
        public static string Enthusiast {
            get {
                return ResourceManager.GetString("Enthusiast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry type.
        /// </summary>
        public static string Entry_type {
            get {
                return ResourceManager.GetString("Entry_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content must be set.
        /// </summary>
        public static string Error_Content_must_be_set {
            get {
                return ResourceManager.GetString("Error:Content_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string Error_Email_not_valid {
            get {
                return ResourceManager.GetString("Error:Email_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid arguments, please check the input.
        /// </summary>
        public static string Error_Invalid_arguments_check_your_input {
            get {
                return ResourceManager.GetString("Error:Invalid_arguments_check_your_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid name.
        /// </summary>
        public static string Error_Invalid_name {
            get {
                return ResourceManager.GetString("Error:Invalid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only have latin letters and digits.
        /// </summary>
        public static string Error_Invalid_username {
            get {
                return ResourceManager.GetString("Error:Invalid_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one translation per language is allowed.
        /// </summary>
        public static string Error_Only_one_translation_per_language_is_allowed {
            get {
                return ResourceManager.GetString("Error:Only_one_translation_per_language_is_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too long.
        /// </summary>
        public static string Error_Password_too_long {
            get {
                return ResourceManager.GetString("Error:Password_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match.
        /// </summary>
        public static string Error_Passwords_dont_match {
            get {
                return ResourceManager.GetString("Error:Passwords_dont_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string Error_Passwords_is_not_valid {
            get {
                return ResourceManager.GetString("Error:Passwords_is_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase shouldn&apos;t be null.
        /// </summary>
        public static string Error_Phrase_shouldn_t_be_null {
            get {
                return ResourceManager.GetString("Error:Phrase_shouldn\'t_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one translation for the entry.
        /// </summary>
        public static string Error_There_must_be_at_least_one_translation {
            get {
                return ResourceManager.GetString("Error:There_must_be_at_least_one_translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation language must be set.
        /// </summary>
        public static string Error_Translation_language_must_be_set {
            get {
                return ResourceManager.GetString("Error:Translation_language_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation text must be set.
        /// </summary>
        public static string Error_Translation_text_must_be_set {
            get {
                return ResourceManager.GetString("Error:Translation_text_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word content must be set.
        /// </summary>
        public static string Error_Word_content_must_be_set {
            get {
                return ResourceManager.GetString("Error:Word_content_must_be_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to perform this operation.
        /// </summary>
        public static string Error_You_are_not_authorized_for_this_operation {
            get {
                return ResourceManager.GetString("Error:You_are_not_authorized_for_this_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_password {
            get {
                return ResourceManager.GetString("Forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Go_back {
            get {
                return ResourceManager.GetString("Go_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grammatical class.
        /// </summary>
        public static string Grammatical_class {
            get {
                return ResourceManager.GetString("Grammatical_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        public static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello{0}!.
        /// </summary>
        public static string Hello_0__ {
            get {
                return ResourceManager.GetString("Hello{0}!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code.
        /// </summary>
        public static string Language_code {
            get {
                return ResourceManager.GetString("Language_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latest.
        /// </summary>
        public static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Log_in {
            get {
                return ResourceManager.GetString("Log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Log_out {
            get {
                return ResourceManager.GetString("Log_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged In.
        /// </summary>
        public static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainer.
        /// </summary>
        public static string Maintainer {
            get {
                return ResourceManager.GetString("Maintainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on moderation.
        /// </summary>
        public static string OnModeration {
            get {
                return ResourceManager.GetString("OnModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or sign up with:.
        /// </summary>
        public static string Or_sign_up_with_ {
            get {
                return ResourceManager.GetString("Or_sign_up_with:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit word.
        /// </summary>
        public static string PageTitle_EditWord {
            get {
                return ResourceManager.GetString("PageTitle:EditWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string Password_reset {
            get {
                return ResourceManager.GetString("Password_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase.
        /// </summary>
        public static string Phrase {
            get {
                return ResourceManager.GetString("Phrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation.
        /// </summary>
        public static string Pronunciation {
            get {
                return ResourceManager.GetString("Pronunciation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to add new entry without a translation?.
        /// </summary>
        public static string Question_Do_you_really_want_to_add_new_entry_without_a_translation_ {
            get {
                return ResourceManager.GetString("Question:Do_you_really_want_to_add_new_entry_without_a_translation?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string References {
            get {
                return ResourceManager.GetString("References", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been successful, please check your email and follow the included link to activate your profile..
        /// </summary>
        public static string Registration_email_sent_message {
            get {
                return ResourceManager.GetString("Registration_email_sent_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string Reset_password {
            get {
                return ResourceManager.GetString("Reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the parent word.
        /// </summary>
        public static string Select_the_parent_word {
            get {
                return ResourceManager.GetString("Select_the_parent_word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set new password.
        /// </summary>
        public static string Set_new_password {
            get {
                return ResourceManager.GetString("Set_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing ....
        /// </summary>
        public static string Start_typing {
            get {
                return ResourceManager.GetString("Start_typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjective.
        /// </summary>
        public static string Word_Adjective {
            get {
                return ResourceManager.GetString("Word:Adjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverb.
        /// </summary>
        public static string Word_Adverb {
            get {
                return ResourceManager.GetString("Word:Adverb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Word_Case {
            get {
                return ResourceManager.GetString("Word:Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsolutiveSingular.
        /// </summary>
        public static string Word_Case_Absolutive {
            get {
                return ResourceManager.GetString("Word:Case:Absolutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allative.
        /// </summary>
        public static string Word_Case_Allative {
            get {
                return ResourceManager.GetString("Word:Case:Allative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative.
        /// </summary>
        public static string Word_Case_Comparative {
            get {
                return ResourceManager.GetString("Word:Case:Comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dative.
        /// </summary>
        public static string Word_Case_Dative {
            get {
                return ResourceManager.GetString("Word:Case:Dative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergative.
        /// </summary>
        public static string Word_Case_Ergative {
            get {
                return ResourceManager.GetString("Word:Case:Ergative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genitive.
        /// </summary>
        public static string Word_Case_Genitive {
            get {
                return ResourceManager.GetString("Word:Case:Genitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumental.
        /// </summary>
        public static string Word_Case_Instrumental {
            get {
                return ResourceManager.GetString("Word:Case:Instrumental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locative.
        /// </summary>
        public static string Word_Case_Locative {
            get {
                return ResourceManager.GetString("Word:Case:Locative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics.
        /// </summary>
        public static string Word_Characteristics {
            get {
                return ResourceManager.GetString("Word:Characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Word_Class {
            get {
                return ResourceManager.GetString("Word:Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Word_Classes {
            get {
                return ResourceManager.GetString("Word:Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjugation.
        /// </summary>
        public static string Word_Conjugation {
            get {
                return ResourceManager.GetString("Word:Conjugation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causative.
        /// </summary>
        public static string Word_Conjugation_Causative {
            get {
                return ResourceManager.GetString("Word:Conjugation:Causative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inceptive.
        /// </summary>
        public static string Word_Conjugation_Inceptive {
            get {
                return ResourceManager.GetString("Word:Conjugation:Inceptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissive.
        /// </summary>
        public static string Word_Conjugation_Permissive {
            get {
                return ResourceManager.GetString("Word:Conjugation:Permissive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PermissiveCausative.
        /// </summary>
        public static string Word_Conjugation_PermissiveCausative {
            get {
                return ResourceManager.GetString("Word:Conjugation:PermissiveCausative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential.
        /// </summary>
        public static string Word_Conjugation_Potential {
            get {
                return ResourceManager.GetString("Word:Conjugation:Potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjunction.
        /// </summary>
        public static string Word_Conjunction {
            get {
                return ResourceManager.GetString("Word:Conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declension.
        /// </summary>
        public static string Word_Declension {
            get {
                return ResourceManager.GetString("Word:Declension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Word_Declension_First {
            get {
                return ResourceManager.GetString("Word:Declension:First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string Word_Declension_Fourth {
            get {
                return ResourceManager.GetString("Word:Declension:Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Word_Declension_Second {
            get {
                return ResourceManager.GetString("Word:Declension:Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string Word_Declension_Third {
            get {
                return ResourceManager.GetString("Word:Declension:Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Word_Degree {
            get {
                return ResourceManager.GetString("Word:Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparative.
        /// </summary>
        public static string Word_Degree_Comparative {
            get {
                return ResourceManager.GetString("Word:Degree:Comparative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concessive.
        /// </summary>
        public static string Word_Degree_Concessive {
            get {
                return ResourceManager.GetString("Word:Degree:Concessive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superlative.
        /// </summary>
        public static string Word_Degree_Superlative {
            get {
                return ResourceManager.GetString("Word:Degree:Superlative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent.
        /// </summary>
        public static string Word_Dependent {
            get {
                return ResourceManager.GetString("Word:Dependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerund.
        /// </summary>
        public static string Word_Gerund {
            get {
                return ResourceManager.GetString("Word:Gerund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        public static string Word_Independent {
            get {
                return ResourceManager.GetString("Word:Independent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interjection.
        /// </summary>
        public static string Word_Interjection {
            get {
                return ResourceManager.GetString("Word:Interjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intransitive.
        /// </summary>
        public static string Word_Intransitive {
            get {
                return ResourceManager.GetString("Word:Intransitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to another word.
        /// </summary>
        public static string Word_Link_to_another_entry {
            get {
                return ResourceManager.GetString("Word:Link_to_another_entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masdar.
        /// </summary>
        public static string Word_Masdar {
            get {
                return ResourceManager.GetString("Word:Masdar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mood.
        /// </summary>
        public static string Word_Mood {
            get {
                return ResourceManager.GetString("Word:Mood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperative.
        /// </summary>
        public static string Word_Mood_Imperative {
            get {
                return ResourceManager.GetString("Word:Mood:Imperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicative.
        /// </summary>
        public static string Word_Mood_Indicative {
            get {
                return ResourceManager.GetString("Word:Mood:Indicative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterrogativeIndicative.
        /// </summary>
        public static string Word_Mood_InterrogativeIndicative {
            get {
                return ResourceManager.GetString("Word:Mood:InterrogativeIndicative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealConditional.
        /// </summary>
        public static string Word_Mood_RealConditional {
            get {
                return ResourceManager.GetString("Word:Mood:RealConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealDesiderative.
        /// </summary>
        public static string Word_Mood_RealDesiderative {
            get {
                return ResourceManager.GetString("Word:Mood:RealDesiderative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnrealConditional.
        /// </summary>
        public static string Word_Mood_UnrealConditional {
            get {
                return ResourceManager.GetString("Word:Mood:UnrealConditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnrealDesiderative.
        /// </summary>
        public static string Word_Mood_UnrealDesiderative {
            get {
                return ResourceManager.GetString("Word:Mood:UnrealDesiderative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word:Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Word_Name_Common {
            get {
                return ResourceManager.GetString("Word:Name:Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proper.
        /// </summary>
        public static string Word_Name_Proper {
            get {
                return ResourceManager.GetString("Word:Name:Proper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noun.
        /// </summary>
        public static string Word_Noun {
            get {
                return ResourceManager.GetString("Word:Noun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склонение.
        /// </summary>
        public static string Word_NounDeclension {
            get {
                return ResourceManager.GetString("Word:NounDeclension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeral.
        /// </summary>
        public static string Word_Numeral {
            get {
                return ResourceManager.GetString("Word:Numeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeral type.
        /// </summary>
        public static string Word_NumeralType {
            get {
                return ResourceManager.GetString("Word:NumeralType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plural.
        /// </summary>
        public static string Word_NumeralType_Plural {
            get {
                return ResourceManager.GetString("Word:NumeralType:Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singular.
        /// </summary>
        public static string Word_NumeralType_Singular {
            get {
                return ResourceManager.GetString("Word:NumeralType:Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Word_NumericalCategory {
            get {
                return ResourceManager.GetString("Word:NumericalCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derivative.
        /// </summary>
        public static string Word_NumericalCategory_Derivative {
            get {
                return ResourceManager.GetString("Word:NumericalCategory:Derivative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplicative.
        /// </summary>
        public static string Word_NumericalCategory_Multiplicative {
            get {
                return ResourceManager.GetString("Word:NumericalCategory:Multiplicative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal.
        /// </summary>
        public static string Word_NumericalCategory_Ordinal {
            get {
                return ResourceManager.GetString("Word:NumericalCategory:Ordinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitive.
        /// </summary>
        public static string Word_NumericalCategory_Quantitative {
            get {
                return ResourceManager.GetString("Word:NumericalCategory:Quantitative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity.
        /// </summary>
        public static string Word_NumericalComplexity {
            get {
                return ResourceManager.GetString("Word:NumericalComplexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        public static string Word_NumericalComplexity_Complex {
            get {
                return ResourceManager.GetString("Word:NumericalComplexity:Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite.
        /// </summary>
        public static string Word_NumericalComplexity_Composite {
            get {
                return ResourceManager.GetString("Word:NumericalComplexity:Composite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string Word_NumericalComplexity_Simple {
            get {
                return ResourceManager.GetString("Word:NumericalComplexity:Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Particle.
        /// </summary>
        public static string Word_Particle {
            get {
                return ResourceManager.GetString("Word:Particle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Word_Person {
            get {
                return ResourceManager.GetString("Word:Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plur..
        /// </summary>
        public static string Word_Plural {
            get {
                return ResourceManager.GetString("Word:Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronoun.
        /// </summary>
        public static string Word_Pronoun {
            get {
                return ResourceManager.GetString("Word:Pronoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemanticType.
        /// </summary>
        public static string Word_SemanticType {
            get {
                return ResourceManager.GetString("Word:SemanticType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualitive.
        /// </summary>
        public static string Word_SemanticType_Qualitive {
            get {
                return ResourceManager.GetString("Word:SemanticType:Qualitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string Word_SemanticType_Relative {
            get {
                return ResourceManager.GetString("Word:SemanticType:Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sing..
        /// </summary>
        public static string Word_Singular {
            get {
                return ResourceManager.GetString("Word:Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tense.
        /// </summary>
        public static string Word_Tense {
            get {
                return ResourceManager.GetString("Word:Tense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future continuous.
        /// </summary>
        public static string Word_Tense_FutureContinuous {
            get {
                return ResourceManager.GetString("Word:Tense:FutureContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future simple.
        /// </summary>
        public static string Word_Tense_FutureSimple {
            get {
                return ResourceManager.GetString("Word:Tense:FutureSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infinitive.
        /// </summary>
        public static string Word_Tense_Infinitive {
            get {
                return ResourceManager.GetString("Word:Tense:Infinitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastImperfect.
        /// </summary>
        public static string Word_Tense_PastImperfect {
            get {
                return ResourceManager.GetString("Word:Tense:PastImperfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastPerfect.
        /// </summary>
        public static string Word_Tense_PastPerfect {
            get {
                return ResourceManager.GetString("Word:Tense:PastPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastRecent.
        /// </summary>
        public static string Word_Tense_PastRecent {
            get {
                return ResourceManager.GetString("Word:Tense:PastRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastRemote.
        /// </summary>
        public static string Word_Tense_PastRemote {
            get {
                return ResourceManager.GetString("Word:Tense:PastRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PastWitnessed.
        /// </summary>
        public static string Word_Tense_PastWitnessed {
            get {
                return ResourceManager.GetString("Word:Tense:PastWitnessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresentContinuous.
        /// </summary>
        public static string Word_Tense_PresentContinuous {
            get {
                return ResourceManager.GetString("Word:Tense:PresentContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresentSimple.
        /// </summary>
        public static string Word_Tense_PresentSimple {
            get {
                return ResourceManager.GetString("Word:Tense:PresentSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitiveness.
        /// </summary>
        public static string Word_Transitiveness {
            get {
                return ResourceManager.GetString("Word:Transitiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intransitive.
        /// </summary>
        public static string Word_Transitiveness_Intransitive {
            get {
                return ResourceManager.GetString("Word:Transitiveness:Intransitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitive.
        /// </summary>
        public static string Word_Transitiveness_Transitive {
            get {
                return ResourceManager.GetString("Word:Transitiveness:Transitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string Word_Undefined {
            get {
                return ResourceManager.GetString("Word:Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb.
        /// </summary>
        public static string Word_Verb {
            get {
                return ResourceManager.GetString("Word:Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reset your password here.
        /// </summary>
        public static string You_can_reset_your_password_here {
            get {
                return ResourceManager.GetString("You_can_reset_your_password_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is activated you can now log in.
        /// </summary>
        public static string Your_account_is_activated_you_can_now_log_in {
            get {
                return ResourceManager.GetString("Your_account_is_activated_you_can_now_log_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully updated.
        /// </summary>
        public static string Your_password_has_been_updated {
            get {
                return ResourceManager.GetString("Your_password_has_been_updated", resourceCulture);
            }
        }
    }
}
